VERSION = "BETA-0.1"
WINDOW_TITLE = f"String Artist | Version: {VERSION}"
CREDITS = "Quintin Dunn - Lead Developer"

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 800
WINDOW_RESIZABLE = True

WORKSPACE_PADDING = 50

TARGET_GUI_FRAMERATE = 240

BACKGROUND_COLOR = (255, 255, 255)  # RGB

# DO NOT CHANGE
WINDOW_DIMS = [WINDOW_WIDTH, WINDOW_HEIGHT]
